terraform {
  source = "../../../../modules/workspace-infra"
}

# Include all settings from the root terragrunt.hcl file
include "root" {
  path = find_in_parent_folders("root.hcl")
}

# Include environment-specific settings
include "env" {
  path   = find_in_parent_folders("env.hcl")
  expose = true
}

# Include region-specific settings
include "region" {
  path   = find_in_parent_folders("region.hcl")
  expose = true
}

# Provider configuration is generated by root.hcl
# Region will be passed via inputs to the module

# Define dependencies
dependency "account_admin" {
  config_path = "../account-admin"

  mock_outputs = {
    admin_group = {
      id = 123456789
    }
  }

  mock_outputs_allowed_terraform_commands = ["init", "validate", "plan", "output", "destroy"]
}

dependency "network" {
  config_path = "../network-infra"

  mock_outputs = {
    vpc_id = "vpc-mock123"
    subnets = [
      "subnet-mock123",
      "subnet-mock456",
    ]
    security_group_ids = [
      "sg-mock123",
    ]
  }

  mock_outputs_allowed_terraform_commands = ["init", "validate", "plan", "output", "destroy"]
}

dependency "metastore" {
  config_path = "../uc-metastore-infra"

  mock_outputs = {
    metastore_id               = "mock-metastore-id"
    unity_catalog_iam_role_arn = "arn:aws:iam::123456789012:role/mock-metastore-role"
  }

  mock_outputs_allowed_terraform_commands = ["init", "validate", "plan", "output", "destroy"]
}

dependency "streaming_lake" {
  config_path = "../streaming-lake-infra"

  mock_outputs = {
    bronze_bucket_name = "mock-streaming-bronze"
    bronze_bucket_arn  = "arn:aws:s3:::mock-streaming-bronze"
  }

  mock_outputs_allowed_terraform_commands = ["init", "validate", "plan", "output", "destroy"]
}

# Pass region, dependency outputs, and workspace-specific wiring to Terraform
inputs = {
  region                     = include.region.locals.aws_region
  prefix                     = "ws-${include.env.locals.environment}-${include.region.locals.aws_region}"
  workspace_name             = "lab"
  databricks_account_id      = include.env.locals.databricks_account_id
  databricks_client_id       = include.env.locals.databricks_client_id
  databricks_client_secret   = include.env.locals.databricks_client_secret
  admin_group_id             = dependency.account_admin.outputs.admin_group.id
  vpc_id                     = dependency.network.outputs.vpc_id
  subnet_ids                 = dependency.network.outputs.subnets
  security_group_ids         = dependency.network.outputs.security_group_ids
  metastore_id               = dependency.metastore.outputs.metastore_id
  roles_to_assume            = [dependency.metastore.outputs.unity_catalog_iam_role_arn]
  lakehouse_prefix           = "energy-market-demo-${include.env.locals.environment}-${include.region.locals.aws_region}"
  streaming_lake_bucket_name = dependency.streaming_lake.outputs.bronze_bucket_name
  streaming_lake_bucket_arn  = dependency.streaming_lake.outputs.bronze_bucket_arn
}

# Other variables are defined in terraform.tfvars file
# Terragrunt will automatically load terraform.tfvars
