# Provider configuration for the Databricks workspace infrastructure module

# Databricks provider configuration
# This provider is aliased as 'mws' for account-level operations
# Note: Provider requirements are now consolidated in versions.tf

# The account-level provider is generated by Terragrunt as databricks.mws.
# The default provider below targets the workspace created by this module and is used
# for Unity Catalog workspace objects such as catalogs, schemas, and volumes.

provider "databricks" {
  host          = local.databricks_workspace_host
  client_id     = var.databricks_client_id
  client_secret = var.databricks_client_secret
  auth_type     = "oauth-m2m"
}
