services:
  france-eco2mix-producer:
    build:
      context: .
    image: energy-market-france-eco2mix-producer:local
    environment:
      ENERGY_MARKET_KAFKA_BOOTSTRAP_SERVERS: ${ENERGY_MARKET_KAFKA_BOOTSTRAP_SERVERS:-${KAFKA_BOOTSTRAP_SERVERS:-}}
      ENERGY_MARKET_KAFKA_TOPIC: ${ENERGY_MARKET_KAFKA_TOPIC:-${KAFKA_TOPIC:-}}
      ENERGY_MARKET_KAFKA_API_KEY: ${ENERGY_MARKET_KAFKA_API_KEY:-${KAFKA_API_KEY:-}}
      ENERGY_MARKET_KAFKA_API_SECRET: ${ENERGY_MARKET_KAFKA_API_SECRET:-${KAFKA_API_SECRET:-}}
    command: ["--last-days", "${LAST_DAYS:-1}"]
